### ISSUE TITLE
In categories filtering adding the loader or spinner

### ISSUE THREAD

**Issue by raneem-yad** [raneem-yad/wissen#45]
when the user try to get courses by category it should see a spinner not freezing screen

**Comment by Sky-De** [comment]
@raneem-yad hi, i would like to work on this, please assign this to me, thanks

**Comment by raneem-yad** [comment]
Thank you @Sky-De  for your Gesture! 
But this project is part of the Project I need to deliver to Code Institute by myself to get a fair grade!
I will close the issue because I've solved it.
